[config]
schemaVersion = "0.0.1"

[general]
repository = "https://thunderstore.io"

[package]
namespace = "Ozone"
name = "Glow_Steps"
description = "Now see other people's footsteps w/ no networking required(Client-side still)! Adds glowing footsteps where you run! Makes getting out easier."
websiteUrl = "https://github.com/NicholasScott1337/Glowsteps"
containsNsfwContent = false

[package.dependencies]
BepInEx-BepInExPack = "5.4.2100"

[build]
icon = "./icon.png"
readme = "../README.md"
outdir = "../dist/"

[[build.copy]]
source  = "../GlowSteps/bin/Debug/netstandard2.1/NicholaScott.LethalCompany.GlowSteps.dll"
target = "/NicholaScott.LethalCompany.GlowSteps.dll"

[[build.copy]]
source = "../CHANGELOG.md"
target = "CHANGELOG.md"

[publish]
communities = ["lethal-company"]

[publish.categories]
lethal-company = ["bepinex", "libraries", "tools"]